import { ArrowUpRight, Github, LockKeyhole, Globe, Smartphone, Code2, Check } from 'lucide-react'
import SectionHeading from './SectionHeading'
import { projects } from '../data/projects'

function ProjectVisual({ index }: { index: number }) {
  if (index === 0) return <div className="architecture-visual" aria-label="Drakewoods architecture: React web and Kotlin Android connected to Google Cloud Functions"><div className="visual-caption"><span className="status-dot" /> FULL-STACK ARCHITECTURE <span>WEB + MOBILE</span></div><div className="architecture-clients"><div><Globe size={23} /><span>React</span><small>WEB APPLICATION</small></div><span className="architecture-plus">+</span><div><Smartphone size={23} /><span>Kotlin</span><small>NATIVE ANDROID</small></div></div><div className="connector-lines"><i /><i /></div><div className="cloud-block"><span className="cloud-symbol">{'{ }'}</span><div><strong>Google Cloud Functions</strong><small>BACKEND SERVICES / FIREBASE</small></div><span className="status-dot" /></div><div className="architecture-foot"><Check size={12} /> One connected digital experience</div></div>
  if (index === 1) return <div className="mend-visual" aria-label="Mend mental health project illustration"><div className="mend-orbit orbit-one" /><div className="mend-orbit orbit-two" /><div className="mend-symbol">m<span>·</span></div><span className="visual-corner">DESIGNED WITH EMPATHY</span><span className="visual-index">02 / MOBILE</span></div>
  return <div className="portfolio-visual" aria-label="Portfolio code illustration"><div className="mini-editor"><div className="mini-editor-bar"><Code2 size={12} /> portfolio.tsx <span>×</span></div><div className="mini-code"><p><i>01</i><span>const</span> developer = {'{'}</p><p><i>02</i>  name: <b>'Rohan'</b>,</p><p><i>03</i>  drivenBy: <b>'curiosity'</b>,</p><p><i>04</i>  alwaysLearning: <span>true</span></p><p><i>05</i>{'};'}</p><p><i>06</i><span>export default</span> developer;</p></div></div><span className="visual-corner">YOU ARE HERE</span><span className="visual-index">03 / WEB</span></div>
}
export default function Projects() {
  return <section id="projects" className="section shell">
    <SectionHeading number="03" label="SELECTED WORK" title="Ideas shipped into the real world."><a className="text-link" href="https://github.com/RohanM007" target="_blank" rel="noreferrer"><Github size={16} /> Explore GitHub <ArrowUpRight size={15} /></a></SectionHeading>
    <div className="project-grid">{projects.map((project, index) => <article className={`project-card ${index === 0 ? 'project-featured' : ''}`} key={project.title}>
      <ProjectVisual index={index} />
      <div className="project-content"><div className="project-kicker"><span>{index === 0 ? 'FEATURED PROJECT' : project.category.toUpperCase() + ' PROJECT'}</span><span>{index === 0 ? '2025' : index === 1 ? 'MOBILE APPLICATION' : 'PERSONAL PORTFOLIO'}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.technologies.map(tech => <span key={tech}>{tech}</span>)}</div>
        <details className="project-details"><summary>Project details <span>+</span></summary><p>{index === 2 ? 'A responsive, Matrix-inspired portfolio with an interactive terminal, accessible navigation, and a focus on telling my story through real projects.' : project.longDescription}</p><ul>{(index === 2 ? ['Interactive terminal with keyboard command history', 'Responsive layouts for desktop, tablet, and mobile', 'Accessible navigation and reduced-motion support', 'React, TypeScript, and Tailwind CSS'] : project.highlights).map(highlight => <li key={highlight}>{highlight}</li>)}</ul></details>
        <div className="project-links">{project.githubLink && <a className="text-link" href={project.githubLink} target="_blank" rel="noreferrer">View source <ArrowUpRight size={15} /></a>}{project.facebookLink && <a className="text-link" href={project.facebookLink} target="_blank" rel="noreferrer">School feature <ArrowUpRight size={15} /></a>}{index === 0 && <><span className="private-label"><LockKeyhole size={13} /> Private repository</span><a className="text-link" href="mailto:rohanmaharaj708@gmail.com?subject=Drakewoods%20code%20sample%20request">Request a walkthrough <ArrowUpRight size={15} /></a></>}{index === 2 && <a className="text-link" href="https://github.com/RohanM007/RohanPortfolio" target="_blank" rel="noreferrer">View source <ArrowUpRight size={15} /></a>}</div>
      </div>
    </article>)}</div>
  </section>
}
